---
title: "Generated Report - Wine Quality"
author: "Xavier Bryant"
date: "17/03/2021"
output: pdf_document
params:
  Xs: Xs 
  Ys: Ys
  winewhite: winewhite
  xsummary: xsummary
  ysummary: ysummary
  xhead: xhead
  yhead: yhead
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(options(knitr.kable.NA = ''))
knitr::opts_chunk$set(fig.width=8, fig.height=4)
library(tidyverse)
library(VGAM)
library(corrplot)
library(ggplot2)
library(knitr)
```


## Data Description



## Plot

Here is the plot you've made based on the variables you've picked.

```{r, echo=FALSE}
ggplot(winewhite,aes_string(x = params$Xs, y = params$Ys, colour = "Quality")) +
             # col_scale +
            geom_point()
```



## Summary of the x and y variables choosen


Below are the summaries of the x and y variables you've choosen.


```{r, echo=FALSE}
x <- params$Xs
y <- params$Ys
x <- eval(parse(text = x))
y <- eval(parse(text = y))
params$Xs
summary(x)
params$Ys
summary(y)
"Quality"
summary(winewhite$Quality)
```


